### ISSUE TITLE
Remove tags from set_outcome() call

### ISSUE THREAD

**Issue by jamesondh** [fluxprotocol/oracle-monorepo-near#61]

**Comment by FranklinWaller** [comment]
Tags are used to help identify what exactly needs to be finalized. In the case of pulse, it's the market ID. Removing this would make it very hard to determine which set_outcome belongs to which market.

**Comment by jamesondh** [comment]
Makes sense, I was thinking about tags from more of an SEO perspective but this has more of an obvious use case I was unaware of (we should probably give a more accurate comment in the code to make it clearer). The main reasoning to remove it was because it is the only variable in the finalization causing gas prices in the cross-contract calls to vary. Currently the max amount of tags allowed is 8, perhaps we should lower this as well to make estimation easier? @jasperdg
