### ISSUE TITLE
Oracle stops alternative answer from being supplied, claiming cannot provide answer from previously bonded outcome

### ISSUE THREAD

**Issue by HeartyMoriarty** [fluxprotocol/oracle-monorepo-near#88]
Request #9679, I continuously provided an answer in resolution windows alternative to what the automated validators staked on, and by the 6th resolution window, received a warning in the stake window saying that I cannot provide answer from previously bonded outcome. I no longer was able to provide any further answers and the resolution window timer stopped showing.

**Comment by FranklinWaller** [comment]
Moving this to https://github.com/fluxprotocol/oracle-explorer-fe/issues/37
